### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by abon22** [tjackadams/autotaskoperations#5]
I can't open the project, can you help me with this?

![2017-01-13_9-20-12](https://cloud.githubusercontent.com/assets/17940369/21914960/8da9720a-d971-11e6-8f60-eae3380d10d8.jpg)

Im using Visual Studio 2013

**Comment by tjackadams** [comment]
@abon22 the project in question is a dot net core project so you will only be able to open it in visual studio 2015 and later.
